name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.1"]
  
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install --upgrade pip && make requirements

    - name: Run validate
      run: make validate
