name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: create venv
      run: make environment

    - name: Install dependencies
      run: make requirements

    - name: Run validate
      run: make validate
